### ISSUE TITLE
Cannot install because of unknown field "tls" i

### ISSUE THREAD

**Issue by yodatak** [kubectyl/charts#1]
Helm install don't work with k3s version v1.25.8+k3s1 (6c5ac022 and nginx ingress

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http): unknown field "tls" in io.k8s.api.networking.v1.HTTPIngressRuleValue, ValidationError(Ingress.spec.rules[1].http): unknown field "tls" in io.k8s.api.networking.v1.HTTPIngressRuleValue]

Hi thanks a lot for your work i want to install it and i automated all the install and retry with nginx ingress or traefik
I can  help for debug if needed

**Comment by andrei0465** [comment]
Sorry for the late reply, I didn't see this issue. The Helm chart is not ready yet, that's why you get that error, it will follow soon.
For more updates you can join the discord server: https://dsc.gg/kubectyl
